Repository esdc-devcop/guides, pull requests merged in 2019-12, with the labels that each got.

#15 Clean cicd
  index.md
  pipelines/cicd.md
Labels: bug, guide

#17 Menu - Right Item
  _data/nav.yml
  _layouts/default.html
Labels: documentation, enhancement

#19 Migrate Present at DevCoP guide
  index.md
  practices/Present-at-DevCoP.md
Labels: documentation, guide

#13 Migrated TFS 2010 Bug Reporting Guide
  assets/bugreporting/450px-Bugprocessbottom.JPG
  assets/bugreporting/450px-Bugprocesstop.JPG
  assets/bugreporting/ActiveBugs_Query.JPG
  assets/bugreporting/BugReasonsStates2.JPG
  assets/bugreporting/BugWindow.JPG
  assets/bugreporting/ReadytotestBugs_Query.JPG
  source-control/Bug_Reporting_TFS_2010.md
Labels: documentation, guide
